/*
 */
package Lab12;

import java.awt.Font;
import java.awt.Point;
import javax.swing.JOptionPane;


/**
 *
 * @author parsh
 */
public class lab12 extends javax.swing.JFrame {

    /**
     * Creates new form lab12
     */
    
    public lab12() {
        
        initComponents();
        jTextArea2.setVisible(false);
        jTextArea3.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Слева в низу", "Справа в низу", "Слева в верху" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 120, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "13", "14", "15" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 120, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Створити проект, який дозволяє користувачу\nзмінювати положення вікна редагування –\nкомпоненту Memo (варіанти пропонуються на вибір) \nі розмір шрифту тексту у вікні (пропонується на вибір) ");
        jTextArea1.setToolTipText("Поле Memo(ну почти)");
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jButton1.setText("Сделать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Створити проект, який дозволяє користувачу\nзмінювати положення вікна редагування –\nкомпоненту Memo (варіанти пропонуються на вибір) \nі розмір шрифту тексту у вікні (пропонується на вибір) ");
        jTextArea2.setToolTipText("Поле Memo(ну почти)");
        getContentPane().add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 500, -1));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Створити проект, який дозволяє користувачу\nзмінювати положення вікна редагування –\nкомпоненту Memo (варіанти пропонуються на вибір) \nі розмір шрифту тексту у вікні (пропонується на вибір) ");
        jTextArea3.setToolTipText("Поле Memo(ну почти)");
        getContentPane().add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FONT(float newSize)
    {
         jTextArea1.setVisible(false);
         jTextArea2.setVisible(false);
         jTextArea3.setVisible(false);
         
         jTextArea1.setFont(new Font(jTextArea1.getFont().getFontName(),Font.BOLD, (int)newSize));
         jTextArea2.setFont(new Font(jTextArea2.getFont().getFontName(),Font.BOLD, (int)newSize));
         jTextArea3.setFont(new Font(jTextArea3.getFont().getFontName(),Font.BOLD, (int)newSize));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float type1 = Float.parseFloat((String)jComboBox4.getSelectedItem());
        FONT(type1);
       
        String type = (String)jComboBox2.getSelectedItem();
        if("Слева в верху".equals(type))
        {
            jTextArea1.setVisible(true);
        }
        if("Слева в низу".equals(type))
        {
            jTextArea2.setVisible(true);
        }
        if("Справа в низу".equals(type))
        {
             jTextArea3.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new lab12().setVisible(false);
            }
        });
    }
    public static void sVisible(boolean a)
    {
        new lab12().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
